language: php

php:
    - 5.5
    - 5.6
    - 7.0

branches:
  only:
    - master

install:
    - composer install -n --dev

script:
    - bin/atoum -c .atoum.travis.php

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml
